bin.js, package.json, test/bin.js
=> Sarbbottam plugin rules

.travis.yml, package.json
=> chore(build): paused semantic release

package.json
=> chore: Update contributors in package.json

README.md, package.json
=> refactor(package): more generic package name

package.json, src/difference.js, src/rule-finder.js, test/difference.js
@ta2edchimp  Do we need `lodash.difference` for our use-case?
=> refactor(deps): using local difference instead of lodash

package.json
=> chore: Remove unnecessary npm script

.travis.yml
=> chore(build): only npm@3

package.json, src/bin.js, test/bin.js
=>  :cop: better test than regret

package.json
Fixed #20 
Just keeping it ready!
=> chore(release): semantic release :tada:

package.json
=> chore(package): update validate-commit-msg to version 2.6.0

test/lib/array-diff.js, test/lib/rule-finder.js
* chore: fix typos
* chore: concretize test description
=> 1/3: Typos & Test Description

README.md, src/lib/rule-finder.js, test/lib/rule-finder.js
* feat: get current rules detailed config
=> 2/3: Get Current Rules' Detailed Config

src/lib/object-diff.js, test/lib/object-diff.js
=> feat(lib): implement object diff detector

src/bin/find.js, test/bin/find.js
Supercedes the `feat(find): add verbose output` commit of #50
=> feat(find): add verbose ouput option

package.json
=> chore(package): update yargs to version 4.6.0

package.json, src/bin/diff.js, src/bin/find.js, src/bin/is-global.js
anywhere in the path
fixed #70
=> fix(eslint): display error if eslint is not found

package.json
see https://github.com/sarbbottam/eslint-find-rules/pull/72#discussion_r62393038
=> fix(deps): `which` should be part of `deps` instead of `devDeps`

src/bin/find.js
is-global check should not have been part of minor release
fixed #83
=> fix(version): skip is-global check

.travis.yml
=> chore(build): install eslint@2.13.1 for node 0.10

src/lib/rule-finder.js, test/lib/rule-finder.js
=> fix(core-rules): updated core rules determination logic

src/bin/find.js, test/bin/find.js
see #195 for the context.
fixes #194
=> fix(options): negation using --no prefix

test/bin/find.js
=> test(no-core): added missing tests for --no-core

src/bin/find.js, src/lib/array-diff.js, src/lib/cli-util.js, src/lib/flatten-rules-diff.js, src/lib/rule-finder.js, test/bin/diff.js, test/bin/find.js
PR to your PR #200 to save @sarbbottam time should he incorporate the proposed changes.
=> refactor(convention): using es-next conventions (cont.)

README.md
This PR is serving a dual purpose.
- fix typo
- verify that auto merge does not happen on approval.
@ta2edchimp @ljharb
=> docs(readme): typo for Acknowledgment

src/lib/normalize-plugin-name.js, src/lib/rule-finder.js, test/lib/rule-finder.js
=> test: Fix ESLint errors

test/lib/rule-finder.js
=> test: eslint v7.12 broke our tests’ proxyquire

.github/workflows/rebase.yml
This has to be merged for #338's actions to run.
It automatically rebases any PR that has a merge commit in it.
=> [actions] add the Automatic Rebase action
