- package.json
- src/bin.js
-c|--current, -p|--plugin, -a|--all-available, -u|--unused
BREAKING: updated package name
> feat(cli): accepts options corresponding to rules

- README.md
and added acknowledgement
fixed #5 
@ta2edchimp please review.
> docs(readme): updated description, badges

- README.md
- src/bin.js
- test/bin.js
use -n|no-error to suppress
fixed #31 
/ @ta2edchimp
> feat(exit): non-zero exit code for getUnusedRules

- src/bin.js
- test/bin.js
Before, no unused rules always returned a non-zero exit code even when
no unused rules were found. Now, -u only returns a non-zero exit code
when an unused rule is found.
This makes eslint-find-rules an even better tool by being able to
be ran on CI when ESLint updates for configs.
> feat(bin): 0 exit code when no unused rules found

- package.json
Ensure to complete report-coverage script to complete, even if semantic-release fails.
(#35 is the last PR including a Coverage Report as post in the discussion)
> chore(ci-build): Make travis-after-all npm scrit to run serially

- package.json
- src/bin/diff.js
- src/bin/find.js
- src/lib/rule-finder.js
- src/lib/sort-rules.js
- test/lib/rule-finder.js
- test/lib/sort-rules.js
Improve output of rules by rendering them in a tabular structure, like ls on *nixes.
Closes #9
> feat(bin): Improve output

- src/lib/sort-rules.js
- test/lib/sort-rules.js
> feat(lib): implement sorting of config diff object

- src/bin/diff.js
- src/bin/find.js
- src/lib/cli-util.js
- test/lib/cli-util.js
Creates a utility wrapper for `cliui` and let's `bin/diff` and `bin/find` use it.
> refactor(output): render output via a utility wrapper

- src/bin/diff.js
- test/bin/diff.js
Implements the two way diffing on
```
eslint-diff-rules config1 config2
```
---
This PR still includes its predecessor's commit — so I guess it (again) should be rebased after #58 got merged (why does this not get resolved automatically??) ...
> feat(diff): compare config in both ways

- src/bin/diff.js
- src/lib/flatten-rules-diff.js
- src/lib/stringify-rule-config.js
- test/bin/diff.js
- test/lib/flatten-rules-diff.js
- test/lib/stringify-rule-config.js
Supercedes the `detailed output` commit of #50
> feat(diff): detailed comparison via verbose output flag

- .all-contributorsrc
- src/lib/rule-finder.js
- test/fixtures/eslint.json
- test/lib/rule-finder.js
I was getting this error:
```
Error: Cannot find module 'eslint-plugin-@scottnonnenberg/thehelp'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at getPluginRule (node_modules/eslint-find-rules/src/lib/rule-finder.js:41:26)
...
```
> feat: Support plugins with scoped names

- package.json
BREAKING CHANGE: eslint ^3.0.0 is desired as peer deps
> chore(peer-deps): updated eslint version

- src/bin/find.js
- src/lib/rule-finder.js
- test/lib/rule-finder.js
feat(find): add `nocore` option (#130)
Allows users to use
```
eslint-find-rules --no-core --unused <file>
eslint-find-rules -C --unused <file>
```
Let me know what you think!
> feat(find): add `nocore` option (#130)

- package.json
- src/bin/find.js
- src/lib/cli-util.js
feat(find): add rule documentation links in verbose mode (fixes #141)
This adds document links to the verbose output. The verbose mode now prints everything in one column (or rather two: one for the rule name, one for the link). This is what it looks like
It's not as pretty as the non-verbose mode, as things are not aligned. Maybe at some point color could be added to the link and/or rule name.
Let me know what you think!
> feat(find): add rule documentation links in verbose mode (fixes #141)

- src/bin/find.js
- src/lib/cli-util.js
- test/bin/find.js
As the title says (I was impatient and thus not able to wait until after the planned "es2015ification") ...
I moved the whole `getRuleURI` logic out of `lib/cli-util` and into `bin/find` (where it belongs imo), altered the `push` method to accept `uniformColWidths` (calculates the columns' widths individually if explicitly set to `false`) — this made the `verbosePush` method obsolete.  
Finally tweaked the tests due to a warning, that the coverage would not meet global threshold (`reduce`ing the array, enriched with the rule documentation links was reported as untested).
> fix(find): make rule documentation output aligned in columns

- src/lib/rule-finder.js
- test/fixtures/eslint-with-plugin-with-no-rules.json
- test/lib/rule-finder.js
I found a crash when having eslint-plugin-json in my config. The reason is that the plugin does not have any rules, and that when do stuff on that value that we did not assume could be  `undefined`.
The fix is pretty simple, it worked for me when I tampered with it in my node_modules, but I can't seem to write any tests for it. I'm getting the following error. Let me know if you have some tips on getting that working :)
```
1) rule-finder specifiedFile (absolute path) without rules - plugin rules:
Error: Failed to load plugin no-rules: Cannot find module 'eslint-plugin-no-rules'
```
> Fix crash when no rules

- package.json
- src/bin/find.js
Underline urls in verbose mode (fixes #178)
Visual result:
> feat(find): underline urls in verbose mode (fixes #178)

- src/bin/find.js
argv.error is true by default
if --no-error is passed argv.error will be false
if -n was passed it would set argv.error to false
fixes #194 
---
@ljharb @ta2edchimp 
Please excuse me for the plethora of PRs over the weekend. Sorry about it.
Hopefully, this is the last one.
> fix(exit-code): determination logic

- .travis.yml
- package.json
- src/bin/diff.js
- src/bin/find.js
- src/lib/array-diff.js
- src/lib/cli-util.js
- src/lib/flatten-rules-diff.js
- src/lib/object-diff.js
- src/lib/rule-finder.js
- src/lib/sort-rules.js
- src/lib/stringify-rule-config.js
- test/bin/diff.js
- test/bin/find.js
- test/lib/array-diff.js
- test/lib/cli-util.js
- test/lib/flatten-rules-diff.js
- test/lib/object-diff.js
- test/lib/rule-finder.js
- test/lib/sort-rules.js
- test/lib/stringify-rule-config.js
fixes #154
@ljharb @ta2edchimp
> refactor(convention): using es-next conventions

- .all-contributorsrc
- package.json
- src/lib/rule-finder.js
- test/lib/rule-finder.js
**Breaking change:** Requires eslint >= 3.12.0
Starting with version 3.12.0, eslint provides a getRules() API that allows us to directly access the rules rather than trying to load them from the file system.  This is cleaner, eliminates a dependency on the internal structure of the eslint codebase.
This change paves the way for further features involving deprecated rules, such as #172 and #188.
Note that eslint returns a `Map` object containing the rules, so we can’t use `Object.keys()` to get the keys out.
We are not yet using the rule objects themselves, so the test stubs just return empty objects for now.
Closes #211.
> refactor(find): Use new eslint getRules() api

- .npmignore
- package.json
Due to a hickup in the automatic release setup, we have to go back to manually releasing (at least version 2.0.0).
> chore(release): releasing 2.0.0 manually

- README.md
- src/bin/find.js
- src/lib/rule-finder.js
- test/bin/find.js
- test/lib/rule-finder.js
Filter out deprecated rules in `_getAllAvailableRules()` and `_getPluginRules()`.  With this change, the lists of rules displayed with the `-a` and `-u` flags will not include deprecated rules.
Breaking: The output is now different from what it was, as deprecated rules are now omitted by default.
Breaking: The `getRuleFinder()` API has changed.  Previously, it took an optional filename and an optional boolean, `noCore`.  Now, it takes the optional filename and an options object:
* `omitCore`: Exclude core rules from the output
* `includeDeprecated`: Include deprecated rules in the output
Both options default to `false` if they are not provided.
Per a review request, I've added a flag to allow deprecated rules to be included.  Adding `--include deprecated` or `-i deprecated` will include …
> feat(rule-finder): Omit deprecated rules

- src/lib/rule-finder.js
Per the discussion that happened after #270 was merged, this reverts the final commit on that PR so that the default `options` parameter is specified on the exported function where clients will see it, rather than on the internal and private `RuleFinder` constructor.
> revert: feat(rule-finder): Default options on exported function

- package.json
Making this a major because of the breaking change of its main feature and the change of the library's exposed API.
---
Proposed Changelog:
* By default, deprecated rules will be omitted from the output of `-a|--all-available`, `-p|--plugin` and `-u|--unused`.  If you want to report on deprecated rules as well, use the `--include=deprecated` or `-i deprecated` flag.
> Prepare 3.0.0

- package.json
- src/lib/rule-finder.js
- test/fixtures/eslint-dedupe-plugin-rules.json
- test/lib/rule-finder.js
See #281 – including preparation for patch release.
---
Proposed Changelog:
* Fixes an issue listing duplicate plugin rules when using ESLint < 4.0.
> fix(rule-finder): dedupe plugin rules

- README.md
- src/bin/find.js
- src/lib/rule-finder.js
- test/bin/find.js
- test/fixtures/eslint-with-deprecated-rules.json
- test/lib/rule-finder.js
Add a new `-d`/`--deprecated` option that reports any deprecated rules being used in the current configuration.
The new option respects the `--no-error` and `--no-core` options.
In order to make this work, I had to refactor everything a bit.  `_getPluginRules()` and `_getCoreRules()` now both return a `Map` of ruleName => ruleDefinition so that we can determine which rules are deprecated when we need.
With that change, I was able to move the handling of the `includeDeprecated` flag into `RuleFinder` rather than passing it off to the `_get*Rules` functions.
Fixes #188 
h/t @casto101 and @cseidholz for pairing on this with me.
> feat(rule-finder): Report any deprecated rules in use

- package.json
This PR let's `master` catch up with [the already released version](https://github.com/sarbbottam/eslint-find-rules/releases/tag/v3.2.0).
> Rectify 3.2.0 version bump

- src/bin/find.js
- test/bin/find.js
In #286, I added support for reporting on deprecated rules.  According to the documentation and tests I wrote, eslint-find-rules is supposed to exit with code 1 when there are deprecated rules (unless the `--no-error` flag is also provided).  However, in real usage, this didn't happen.
I discovered that the exit status assertions in the tests were not actually being called in all cases, resulting in the tests passing incorrectly.  Looks like I forgot to make sure that the test failed for the right reason in this case.  Mea culpa :-(.
I made the following changes:
- Modify the tests to always capture the process exit code
- Add assertions against the captured exit code where necessary
- Re-work how `processExitCode` is managed in the code
> fix(exit-code): Exit with status 1 when there are deprecated rules

- package.json
Proposed Changelog:
* Correctly exit eslint-find-rules with code 1 when reporting on deprecated rules ( `--include=deprecated` or `-i deprecated`) and there are deprecated rules (unless the `--no-error` flag is also provided).
> Prepare 3.2.1

- src/bin/find.js
Moves the rendering of the output out of the the loop, where all the options' output is collected.  
Also moves the logic into the `else` block after testing the tool's invocation with sufficient arguments. This way, the accompanying tests can be left untouched (they override `process.exit`) _and_ there's only a single location left where `process.exit` has to be called, with an exit code appropriate to the situation.
Fixes #291 
---
Side-to-side comparison may be a bit off due to the whitespace changes. [This url](https://github.com/sarbbottam/eslint-find-rules/pull/292/files?w=1) highlights everything but whitespace changes.
> fix(find): prevent duplicate output

- package.json
Proposed Changelog:
* Output is now properly collected before printed on screen, preventing duplication when multiple options (like `--plugin`, `--unused`) are specified.
> Prepare 3.2.2

- src/lib/cli-util.js
- test/lib/cli-util.js
`eslint-find-rules --unused rules.js` should not output an empty line when there are no unused rules.
> fix(cli): Prevent empty output

- .travis.yml
- package.json
- src/lib/rule-finder.js
- test/lib/rule-finder.js
Fixes #304. Unblocks https://github.com/airbnb/javascript/issues/2036.
Thanks to @lddubeau for the help!
> eslint 6 support

- src/lib/normalize-plugin-name.js
- src/lib/rule-finder.js
- test/fixtures/v5+/eslint-with-deprecated-rules.json
- test/fixtures/v5+/eslint.json
- test/lib/rule-finder.js
Use eslint's internal functions to support shorthand eslint plugin naming.
fix #303
> fix(rule-finder): Support scoped packages with dashes

- .travis.yml
- package.json
ESLint v7.0.0 is [released](https://eslint.org/blog/2020/05/eslint-v7.0.0-released) 🎉
---
Closes #318
Unblocks https://github.com/airbnb/javascript/issues/2223
Unblocks https://github.com/kentcdodds/eslint-config-kentcdodds/pull/64
> feat: Support ESLint 7.x

- README.md
- src/bin/find.js
- src/lib/rule-finder.js
- test/bin/find.js
- test/lib/rule-finder.js
> feat(rule-finder): add --ext option

- .travis.yml
- package.json
- src/lib/normalize-plugin-name.js
Issue #331
ESLint 7.8.0 removed the normalization functions this package used for package/plugin naming. The naming functions have now been moved into @eslint/eslintrc package. This change includes eslintrc as a dependency and removes the old logic of finding the function in the eslint source code.
> fix: ESLint 7.8.0 removes normalization function

- .babelrc
- .eslintrc
- package.json
Resolve https://github.com/MichaelDeBoey/eslint-find-rules/pull/13#discussion_r744166294
* Switch to use `babel-preset-env`, since `babel-preset-es2015` has been deprecated and the former supports es2017 and more configurations
* Exclude `transform-regenerator` in babel config since `transform-regenerator` requires a runtime polyfill and isn't actually needed if we don't use [`Generator.prototype.return()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator/return)
* Update eslint target ecma version to 2017
> chore: update babel and eslint to support es2017

- src/lib/rule-finder.js
As @PaperStrike mentioned in https://github.com/sarbbottam/eslint-find-rules/pull/337#commitcomment-59619616
> refactor: remove unneeded fallback code

- src/lib/rule-finder.js
- test/fixtures/post-v5/eslint-with-overrides.json
- test/fixtures/post-v5/no-path/index.txt
- test/lib/rule-finder.js
> [New] check unused rules with overrides

- .npmignore
- package.json
- this package already uses `yargs@16.2.0`,
- `yargs@16.2.0` uses `cliui@7.0.2`
- so we should align the `cliui` versions so only one gets installed as transient dependency
so there should be no impact to consumers
> build(deps): align `cliui` version to the version `yargs` uses internally

- README.md
- package.json
- src/bin/find.js
- src/lib/rule-finder.js
- test/fixtures/post-v8/eslint-flat-config.js
- test/lib/rule-finder.js
- Handle flat config in `rule-finder.js`
- Add a new `--flatConfig` flag
- Load ESLint class using FlatESLint class
- Add unit tests for basic flat config
> feature: Support Flat configs in v8
